# Site
repository: saifrehman945/saifrehman945.github.io
# favicon: images/favicon.ico

seo:
  name: "Saif ur Rehman"
  description: "CAE Engineer | Researcher | Developer specializing in CFD, FEA, HPC, and workflow automation"

# Content configuration version
version: 2

# Personal info
name: Saif ur Rehman
title: CAE Engineer | Researcher | Developer
email: saifurrehman945@outlook.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username:  saifrehman945
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: saifrehman945
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0009-0002-2344-8775
# googlescholar_username: WM-zoAAAAJ

# Additional icon links
additional_links:
- title: Google scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=WM-zoAAAAJ&user=--WM-zoAAAAJ
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a CAE Engineer and Researcher with **3+ years** of professional experience, specializing in CFD modeling and optimization 
  with applications in energy, automotive, and naval hydrodynamics. 
  I have developed automated CAE pipelines in Python/C++ and contributed to material modeling, experimental validation, and integration of 
  optimization algorithms to enhance structural and fluid-dynamic performance. I am particularly motivated by the intersection of 
  computational mechanics, data-driven methods, and HPC, bridging academic research with industrial applications.

  **Expertise & Technologies**: CFD, FEA, HPC, Python, C++, Optimization, Adjoint Methods, Material Modeling, Automation
content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Simulation Engineer
        sub_title: SOCO Engineers
        caption: December 2023 - present
        link: soco-engineers.com
        # quote: >
        #   A leader in CAE Methods (CFD, crash, NVH, and structure)
        description: | 

          At SOCO Engineers I work on automating **CAE workflows** and integrating **simulation tools** into **engineering processes**. I develop and maintain **C++** and **Python** components for **adjoint-based optimization**, **material modelling**, and **preprocessing/meshing pipelines** to improve repeatability and scalability. I support result validation, **postprocessing workflows**, and collaborate with engineers to deploy tools on **HPC systems**.

          **Key contributions:**
          - Automated **preprocessing and meshing pipelines** (**Python**) to improve setup consistency.
          - Core development of an **adjoint optimization framework** (**C++ core, Python wrappers**).
          - Built **postprocessing and analysis workflows** for rapid verification and reporting.
          - Integrated **material data management** and validation into **FEA workflows**.
          - Collaborated with engineering and **HPC teams** to deploy tools and provide user support/mentoring.


      - layout: left
        title: Research Assistant
        sub_title: National University of Sciences and Technology (NUST)
        caption: November 2022 - December 2023
        link: smme.nust.edu.pk
        # quote: >
        #   A leader in CAE Methods (CFD, crash, NVH, and structure)
        description: | # this will include new lines to allow paragraphs
          As a Research Assistant at SMME NUST, I contributed to various projects focused on **Heat Transfer** and **Multiphase Problems**, 
          providing solutions primarily through **Computational Fluid Dynamics (CFD)** tools. I was a part of a 10-member research team, 
          collaborating on innovative approaches to complex engineering challenges.

          **Key contributions:**

          - [Effect of **Nanofluids** on **Heat Transfer Enhancement** in Solar Heaters](https://doi.org/10.1007/s10973-025-14571-4)
          - [Analyses of **Ventilated Super Cavitation** in Underwater vehicles](https://github.com/saifrehman945/VentilatedSupercavitation)
          - [Particle deposition study in the human trachea](https://pubs.aip.org/aip/pof/article/36/4/043338/3284891)


  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Synergistic effects of Al2O3-ethylene glycol/water nanofluids and artificial roughness on solar heater thermal performance
        # link: https://doi.org/10.1007/s10973-025-14571-4
        # link_text: Research Article Published in Journal of Thermal Analysis and Calorimetry
        additional_links:
          - title: Springer
            icon: fas fa-external-link-alt
            url: https://doi.org/10.1007/s10973-025-14571-4
          - title:  Scholar
            icon: fas fa-book 
            url: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=--WM-zoAAAAJ&citation_for_view=--WM-zoAAAAJ:0EnyYjriUFMC
        quote: >
          Research Article Published in Journal of Thermal Analysis and Calorimetry
        description: | # this will include new lines to allow paragraphs
          This **CFD** study engineered a high-performance solar heater by synergizing **Al₂O₃ nanofluids** with **artificial ribs**. The optimal design—inverted triangular ribs and a 40% EG/60% Water nanofluid—achieved a 71.6% boost in **heat transfer**. Analysis of **turbulent kinetic energy** revealed intense **micro-vortices** enhancing thermal exchange. The configuration yielded a superior **Performance Evaluation Criterion (PEC = 1.5)**, proving its efficiency outweighs pumping costs.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top-middle
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
        #               # other value (or no value) means no border will be displayed
        title: Material Data Management and Simulation Framework
        # link: https://github.com/saifrehman945/FluentVortexShedding
        # link_text: saifrehman945/FluentVortexShedding
        # additional_links:
        #   - title:  Github
        #     icon: fab fa-github
        #     url: https://github.com/saifrehman945/FluentVortexShedding
        quote: >
          Technologies: Python, PostgreSQL, C++, LS-DYNA, ABAQUS
        description: | # this will include new lines to allow paragraphs
           <style>
              /* Popup background */
              .popup {
                display: none;
                position: fixed;
                z-index: 9999;
                left: 0;
                top: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0,0,0,0.85);
              }
              .popup img {
                display: block;
                margin: 5% auto;
                max-width: 90%;
                max-height: 90%;
                border-radius: 10px;
                box-shadow: 0 6px 18px rgba(0,0,0,0.4);
              }
            </style>

            <div style="display:flex; align-items:center; gap:30px;">
              <!-- Left side: text -->
              <div style="flex:3; font-size:16px; line-height:1.5;">
                Managing <b>material data</b> from hundreds of sources is often fragmented, error-prone, and limits reliable <b>FEA simulations</b>.
                I led the development of a comprehensive <b>material data management and simulation framework</b>, 
                consolidating test data from over 300 materials sourced from suppliers, institutes, and in-house 
                experiments into a systematic database. This involved creating and maintaining <b>material cards</b> for 
                advanced <b>FEA simulations</b> on multiple loadcases, designing <b>automated workflows</b> to streamline data collection, 
                validation, and updates, and integrating <b>database algorithms</b> to enable efficient handling of complex datasets. 
                By correlating <b>simulation results</b> with <b>experimental data</b>, I established a reliable workflow that significantly 
                reduced dependency on physical testing while ensuring accuracy in <b>predictive modelling</b>. This project not only enhanced 
                the scalability and traceability of <b>material data management</b> but also accelerated <b>simulation-driven design</b> across multiple engineering domains.
              </div>
              
              <!-- Right side: image -->
              <div style="flex:2; text-align:right; display:flex; justify-content:center; align-items:center;">
                <a href="javascript:void(0)" onclick="document.getElementById('flowchart-popup').style.display='block'">
                  <img src="/assets/images/flowchart.png" 
                      alt="Material Modelling Workflow" 
                      style="width:520px; max-width:100%; border-radius:10px; box-shadow:0 4px 12px rgba(0,0,0,0.2);" />
                </a>
              </div>
            </div>

            <!-- Hidden popup -->
            <div id="flowchart-popup" class="popup" onclick="this.style.display='none'">
              <img src="/assets/images/flowchart.png" alt="Material Modelling Workflow Full" />
            </div>

      - layout: top-middle
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
        #               # other value (or no value) means no border will be displayed
        title: Adjoint-Based Shape Optimization Framework
        # link: https://github.com/saifrehman945/VentilatedSupercavitation
        # link_text: saifrehman945/VentilatedSupercavitation
        additional_links:
          # - title: Springer
          #   icon: fas fa-external-link-alt
          #   url: https://doi.org/10.1007/s10973-025-14571-4
          # - title:  Github
          #   icon: fab fa-github
          #   url: https://github.com/saifrehman945/VentilatedSupercavitation
        quote: >
          Technologies: C++, Python, Adjoint solvers
        description: | # this will include new lines to allow paragraphs
          
          I contributed as a core developer to an **optimization framework** that leverages 
          **adjoint sensitivities** from the solver to drive **gradient-based optimization** of 
          geometry shape and thickness. The framework was implemented in **C++** for computational 
          performance and wrapped in **Python** for accessibility and **workflow automation**. 
          My role involved maintaining and extending the core codebase, integrating new 
          **optimization features**, and ensuring scalability and robustness of the framework. 
          By coupling solver outputs with a streamlined **optimization pipeline**, I enabled 
          efficient and automated design iterations, reducing manual overhead and advancing 
          **solver-driven design optimization** capabilities.

      - layout: top-middle
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
        #               # other value (or no value) means no border will be displayed
        title: Drag Reduction in Underwater Vehicles - Ventilated Cavitation
        link: https://github.com/saifrehman945/VentilatedSupercavitation
        link_text: saifrehman945/VentilatedSupercavitation
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/saifrehman945/VentilatedSupercavitation
        quote: >
          Technologies: ANSYS FLuent, Gnuplot
        description: | # this will include new lines to allow paragraphs
          Underwater vehicles face severe drag penalties that limit speed and efficiency, making **drag reduction** a critical design challenge.
          In this industrial research study, I engineered and validated a **CFD** 
          computational model to harness **ventilated supercavitation** for underwater **drag reduction**. 
          By integrating **multiphase CFD simulations** with **unsteady RANS-VOF methodologies**, 
          I achieved a remarkable 27% reduction in drag—pushing the boundaries of **hydrodynamic efficiency**. 
          The study unveiled critical insights into **cavity dynamics**, **ventilation rates**, and **cavitator geometries**.
      - layout: top-middle
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
        #               # other value (or no value) means no border will be displayed
        title: Case setup for Hagen-Poiseuille Flow in OpenFOAM v12
        link: https://github.com/saifrehman945/HagenPoiseuilleValidation
        link_text: saifrehman945/HagenPoiseuilleValidation
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/saifrehman945/HagenPoiseuilleValidation
        quote: >
          Technologies: OpenFOAM, Python, Gnuplot, Bash
        description: | # this will include new lines to allow paragraphs
          This project modernizes the classic **Hagen-Poiseuille flow** validation by upgrading **OpenFOAM** tutorials 
          from v6 to v12. I revamped control files, streamlined **mesh handling**, and introduced **runtime sampling** for 
          cleaner, more efficient simulations. Legacy scripts were replaced with **Python notebooks** and **Gnuplot visualizations**, 
          making post-processing seamless and interactive. Redundant files were eliminated, simplifying the workflow and boosting 
          maintainability. The result is a reproducible, user-friendly pipeline for validating **laminar flow** fundamentals. 

      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Vortex-Shedding Simulation around Underwater Cylinders
        link: https://github.com/saifrehman945/FluentVortexShedding
        link_text: saifrehman945/FluentVortexShedding
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/saifrehman945/FluentVortexShedding
        quote: >
          Technologies: ANSYS Fluent, Python
        description: | # this will include new lines to allow paragraphs
          **Vortex-induced vibrations (VIV)** around underwater cylinders pose major risks to marine structures, affecting stability, fatigue life, and overall performance.
          The project simulates **vortex shedding** around underwater cylinders at Re = 10,000 using the **RANS-SST turbulence model**. 
          It captures **unsteady flow patterns**, **pressure fluctuations**, and **vortex-induced vibrations** critical to **marine engineering**. 
          Created animations and plots to visualize **vortex formation** and **shedding frequencies**. Results were benchmarked against 
          **experimental data** to validate accuracy. The project provides a benchmark for modelling **VIV phenomena**.

  - title: Education
    layout: list
    content:
      - layout: left
        title: School of Mechanical and Manufacturing Engineering (SMME), NUST
        sub_title: Bachelors in Mechanical Engineering
        caption: 2019 - 2023
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          <table style="width:100%; border-collapse:collapse; font-size:16px;">
            <thead>
              <tr>
                <th style="text-align:left; padding:4px; border-bottom:1px solid #ccc;">Core Subjects</th>
                <th style="text-align:left; padding:4px; border-bottom:1px solid #ccc;">Specialization</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style="padding:4px; vertical-align:top;">Mechanics, Materials, Manufacturing</td>
                <td style="padding:4px; vertical-align:top;">Finite Element Analysis, Computational Fluid Mechanics</td>
              </tr>
              <tr>
                <td style="padding:4px; vertical-align:top;">Machine Design, Mechanics of Machines</td>
                <td style="padding:4px; vertical-align:top;">Numerical Methods, Heat Transfer</td>
              </tr>
              <tr>
                <td style="padding:4px; vertical-align:top;">Thermodynamics, Fluids</td>
                <td style="padding:4px; vertical-align:top;">Programming, Gas Turbines</td>
              </tr>
            </tbody>
          </table>

  - title: Languages
    layout: text
    content: |
      **English:** Certified Language expert ([**IELTS**](https://drive.google.com/file/d/11sNK-16Jhjl5W4Z_t_tQvkXyQ7JMAv7B/view?usp=drive_link))

      **Urdu:** Native
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not working, you'll probably find me on a **badminton** court or getting lost in a good **history** book. I love staying active and learning about the past just for fun.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
